version: '3.4'
services:
  react18:
    build:
      context: .
    container_name: IP-Track-CRM
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:5173 # 8080 is the port on the host machine, 5173 is the port on the container. Change host machine port to whatever you want.
    stdin_open: true
    tty: true
    restart: always

